# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78dc197ad3d9b8793f328a01dfbcccd55145628fe74af3e65cc0655130909d06e9612ed3d922746190e794df31ee8156767275c0969642c3ddc5d2af2afdd83a

test:
  secret_key_base: d05352bbf421bc4d219fcab90523b691932c0ab031d834e581f9187909f0225ba75db311062f7d50e2c4003663239b7548bb346e3f3e90db6c599a3266eabe5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
